In [0]:
# IMPORTANDO BIBLIOTECAS 

import pyspark.sql.functions
from pyspark.sql.types import StructType, StructField , StringType , IntegerType , FloatType
from pyspark.sql import SparkSession
from pyspark.sql.functions import *


# CRIANDO SESSÃO DO SPARK 

spark = (SparkSession.builder
        .master("local(*)")
        .appName('pyspark-12')
        .getOrCreate()
        )

In [0]:
# CRIANDO DATAFRAME 

dados = (

    ['6','05/01/2010','Francisca',12,'NOK'],
    ['13','12/05/2001','Cleiton',21,'OK'],
    ['8','12/06/2015','Roberto',7,'NOK'],
    ['15','07/09/1994','Claudia',28,'OK'],
    ['10','15/02/2005','Tulio',17,'NOK']
    
)


colunas = (StructType([
    StructField('Codigo' , StringType(), True),
    StructField('Data_nasc' , StringType(), True),
    StructField('Nome' , StringType(), True),
    StructField('Idade' , IntegerType(), True),
    StructField('Status' , StringType(), True)
]))

## DATAFRAME FINAL 

df = spark.createDataFrame(data = dados , schema = colunas)

df.display()

Codigo,Data_nasc,Nome,Idade,Status
6,05/01/2010,Francisca,12,NOK
13,12/05/2001,Cleiton,21,OK
8,12/06/2015,Roberto,7,NOK
15,07/09/1994,Claudia,28,OK
10,15/02/2005,Tulio,17,NOK

In [0]:
# 1) CRIE COLUNAS PARA (DIA) / (MES) / (ANO) ==> 3 formas de PEGAR ==> (SUBSTRING , SPLIT , TO_DATE + DATE_FORMAT)

# E ORDENE O (ANO) DO MENOR PARA O MAIOR

"""
df = df.withColumn('Dia', substring('Data_nasc' , 1, 2))\
            .withColumn('Mês' , substring('Data_nasc' , 4 , 2))\
            .withColumn('Ano' , substring('Data_nasc' , 7, 4))\
            .orderBy('Ano')

df.display()
"""

## UTILIZANDO (SPLIT)

"""
df = df.withColumn('Dia' , split(col('Data_nasc') , '/').getItem(0))\
                .withColumn('Mês' , split(col('Data_nasc') , '/').getItem(1))\
                .withColumn('Ano' , split(col('Data_nasc') , '/').getItem(2))\
                .orderBy(col('Ano')).display()
"""

# UTILIZANDO TO_DATE + DATE_FORMAT 


df = df.withColumn('Data_nasc' , to_date('Data_nasc' , 'MM/dd/yyyy'))

# df = df.withColumn('Data_nasc' , to_date(col('Data_nasc') , 'MM/dd/yyyy'))

df = df.withColumn('Dia' , date_format('Data_nasc', 'dd'))\
                .withColumn('Mês' , date_format('Data_nasc' , 'MM'))\
                .withColumn('Ano' , date_format('Data_nasc' , 'yyyy')).display()

Codigo,Data_nasc,Nome,Idade,Status,Dia,Mês,Ano
6,2010-05-01,Francisca,12,NOK,01,05,2010
13,2001-12-05,Cleiton,21,OK,05,12,2001
8,2015-12-06,Roberto,7,NOK,06,12,2015
15,1994-07-09,Claudia,28,OK,09,07,1994
10,null,Tulio,17,NOK,null,null,null

In [0]:
## CONTINUAR DPS (FAZER MAIS COISAS) ==> conferir SLIDE DATAS COM AS FUNCOES DE DATA AQUI