In [0]:
## FUNÇÕES UTILIZADAS ==> (UNION) / (INNER JOIN) / (LEFT/JOIN) / (RIGHT JOIN)

# VIDEO DO YOUTUBE ==> https://www.youtube.com/watch?v=NFiig8yRwmA&list=PLOqx8yEV2-l2Oce3vUNR7L7Qjx_sy8-WO&index=7

In [0]:
# IMPORTANDO BIBLIOTECAS 

import pyspark.sql.functions
from pyspark.sql.types import StructType, StructField , StringType , IntegerType , FloatType
from pyspark.sql import SparkSession
from pyspark.sql.functions import *


# CRIANDO SESSÃO DO SPARK 

spark = (SparkSession.builder
        .master("local(*)")
        .appName('VIDEO7')
        .getOrCreate()
        )

In [0]:
# CRIANDO DATAFRAME 

dados = (

    [1,'James','Vendas','NY',90000,34,10000],
    [2,'Michael','Vendas','NY',86000,56,20000],
    [3,'Robert','Vendas','CA',81000,30,23000],
    [4,'Maria','Financas','CA',90000,24,23000]
)


colunas = (StructType([
    StructField('Cod' , StringType(), True),
    StructField('Nome' , StringType(), True),
    StructField('Departamento' , StringType(), True),
    StructField('Estado' , StringType(), True),
    StructField('Salario' , IntegerType(), True),
    StructField('Idade' , IntegerType(), True),
    StructField('Bonus' , IntegerType(), True)
    
]))

## DATAFRAME FINAL 1

df1 = spark.createDataFrame(data = dados , schema = colunas)


# ============================== ++ ============================ ++ ==============================

# CRIANDO DATAFRAME 2

dados1 = (

    [1,'James','Vendas','NY',90000,34,10000],
    [2,'Maria','Financas','CA',90000,24,23000],
    [3,'Jen','Financas','NY',79000,53,15000],
    [4,'Jeff','Marketing','CA',80000,25,18000],
    [5,'Kumar','Marketing','NY',91000,50,21000]
)


colunas1 = (StructType([
    StructField('Cod' , StringType(), True),
    StructField('Nome' , StringType(), True),
    StructField('Departamento' , StringType(), True),
    StructField('Estado' , StringType(), True),
    StructField('Salario' , IntegerType(), True),
    StructField('Idade' , IntegerType(), True),
    StructField('Bonus' , IntegerType(), True)
    
]))

## DATAFRAME FINAL 2

df2 = spark.createDataFrame(data = dados1 , schema = colunas1)

In [0]:
df1.display()

df2.display()

Cod,Nome,Departamento,Estado,Salario,Idade,Bonus
1,James,Vendas,NY,90000,34,10000
2,Michael,Vendas,NY,86000,56,20000
3,Robert,Vendas,CA,81000,30,23000
4,Maria,Financas,CA,90000,24,23000

Cod,Nome,Departamento,Estado,Salario,Idade,Bonus
1,James,Vendas,NY,90000,34,10000
2,Maria,Financas,CA,90000,24,23000
3,Jen,Financas,NY,79000,53,15000
4,Jeff,Marketing,CA,80000,25,18000
5,Kumar,Marketing,NY,91000,50,21000

In [0]:
## UNIÁO DOS DOIS DATAFRAMES ==> PORQUE POSSUEM O MESMO SCHEMA.. ==> ENTÃO UTILIZA O (UNION)

print('União dos DOIS DATAFRAMES ')

uniao = df1.union(df2)

uniao.display()

União dos DOIS DATAFRAMES

Cod,Nome,Departamento,Estado,Salario,Idade,Bonus
1,James,Vendas,NY,90000,34,10000
2,Michael,Vendas,NY,86000,56,20000
3,Robert,Vendas,CA,81000,30,23000
4,Maria,Financas,CA,90000,24,23000
1,James,Vendas,NY,90000,34,10000
2,Maria,Financas,CA,90000,24,23000
3,Jen,Financas,NY,79000,53,15000
4,Jeff,Marketing,CA,80000,25,18000
5,Kumar,Marketing,NY,91000,50,21000

# Unindo (colunas) de Tabelas diferentes ==> Que possuem (chave primaria em comum) ==> (JOIN)

In [0]:
# 1) FAÇA O (INNER JOIN) DOS DOIS DATAFRAMES 

juncao = df1.join(df2 , df1.Cod == df2.Cod , "inner") ## LEMBRANDO ==> ("inner") ==> TRAZ SOMENTE OS VALORES EM COMUM (DAS DUAS TABELAS)

juncao.display()

Cod,Nome,Departamento,Estado,Salario,Idade,Bonus,Cod,Nome,Departamento,Estado,Salario,Idade,Bonus
1,James,Vendas,NY,90000,34,10000,1,James,Vendas,NY,90000,34,10000
2,Michael,Vendas,NY,86000,56,20000,2,Maria,Financas,CA,90000,24,23000
3,Robert,Vendas,CA,81000,30,23000,3,Jen,Financas,NY,79000,53,15000
4,Maria,Financas,CA,90000,24,23000,4,Jeff,Marketing,CA,80000,25,18000

In [0]:
# 2) FAÇA O (RIGHT JOIN) SOBRE OS 2 DATAFRAMES  ==> LEMBRANDO QUE (RIGHT) ==> VAI TRAZER TODOS OS DADOS DA TABELA (DIREITA) MESMO QUE NAO SEJA EM COMUM COM A #TABELA(ESQUERDA)

# OBS (LEFT JOIN) == (LEFT OUTER JOIN) ; (RIGHT JOIN) == (RIGHT OUTER JOIN)
 
left = df1.join(df2 , df1.Cod == df2.Cod , "right").display()  # DF2 ==> TABELA A (DIREITA)

Cod,Nome,Departamento,Estado,Salario,Idade,Bonus,Cod,Nome,Departamento,Estado,Salario,Idade,Bonus
1,James,Vendas,NY,90000,34,10000,1,James,Vendas,NY,90000,34,10000
2,Michael,Vendas,NY,86000,56,20000,2,Maria,Financas,CA,90000,24,23000
3,Robert,Vendas,CA,81000,30,23000,3,Jen,Financas,NY,79000,53,15000
4,Maria,Financas,CA,90000,24,23000,4,Jeff,Marketing,CA,80000,25,18000
null,null,null,null,null,null,null,5,Kumar,Marketing,NY,91000,50,21000