In [0]:
## FUNÇÕES UTILIZADAS ==> (distinct / dropDuplicates ) ==> o distinct (pega todas as linhas de todas as colunas e tira as repetidas)
                                                      # o dropDuplicates ==> (faz a mesma coisa q o (distinct) , porem, voce pode selecionar qual COLUNA QUER ESPECIFICAR)

In [0]:
# IMPORTANDO BIBLIOTECAS 

import pyspark.sql.functions
from pyspark.sql.types import StructType, StructField , StringType , IntegerType , FloatType
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

In [0]:
# CRIANDO SESSÃO DO SPARK 

spark = (SparkSession.builder
        .master("local(*)")
        .appName('pyspark-8')
        .getOrCreate()
        )

In [0]:
# CRIANDO DATAFRAME 

dados = (

    ['James','Vendas','3000'],
    ['Michael','Vendas','4600'],
    ['Robert','Vendas','4100'],
    ['Maria','Financas','3000'],
    ['James','Vendas','3000'],
    ['Scott','Financas','3300'],
    ['Jonatas','Financas','3900'],
    ['Jefferson','Marketing','3000'],
    ['Caio','Marketing','2000'],
    ['Lucio','Vendas','4100']
)


colunas = (StructType([
    StructField('Nome' , StringType(), True),
    StructField('Departamento' , StringType(), True),
    StructField('Salario' , StringType(), True)
]))

## DATAFRAME FINAL 

df = spark.createDataFrame(data = dados , schema = colunas)

df.display()

Nome,Departamento,Salario
James,Vendas,3000
Michael,Vendas,4600
Robert,Vendas,4100
Maria,Financas,3000
James,Vendas,3000
Scott,Financas,3300
Jonatas,Financas,3900
Jefferson,Marketing,3000
Caio,Marketing,2000
Lucio,Vendas,4100

In [0]:
# 1) MOSTRE APENAS OS VALORES DISTINTOS   ==> Usando (distinct() = dropDuplicates())

dif = df.distinct()

# PRINTANDO O RESULTADO COM PYTHON  ==> obs precisa converter o (dataframe para STRING)
print("APENAS OS UNICOS : " + str(dif.count()))

dif.display()

APENAS OS UNICOS : 9

Nome,Departamento,Salario
James,Vendas,3000
Michael,Vendas,4600
Robert,Vendas,4100
Maria,Financas,3000
Scott,Financas,3300
Jonatas,Financas,3900
Jefferson,Marketing,3000
Lucio,Vendas,4100
Caio,Marketing,2000

In [0]:
# 2) TRAZENDO APENAS VALORES (UNICOS) DAS COLUNAS (DEPARTAENTO E SALARIO) ==> REMOVOU VALORES QUE SE REPETEM NAS DUAS COLUNAS

df_drop = df.dropDuplicates(["Departamento", "Salario"]).display()

# df_dist = df.distinct(["Departamento","Salario"]).display() ==> NÃO PODE USAR DISTINCT PARA FAZER O MESMO.. 

# O DISTINCT ==> OLHA EM TODAS AS LINHAS E COLUNAS E (REMOVE OS VALORES DUPLICADOS )

# O DROPDUPLICATES ==> FAZ O MESMO, POREM, VOCÊ PODE SELECIONAR QUAIS (COLUNAS) QUER REMOVER OS VALORES DUPLICADOS.

Nome,Departamento,Salario
Maria,Financas,3000
Scott,Financas,3300
Jonatas,Financas,3900
Caio,Marketing,2000
Jefferson,Marketing,3000
James,Vendas,3000
Robert,Vendas,4100
Michael,Vendas,4600