In [0]:
## FUNÇÕES UTILIZADAS ==> (UNION) / (DISTINCT)

In [0]:
# IMPORTANDO BIBLIOTECAS 

import pyspark.sql.functions
from pyspark.sql.types import StructType, StructField , StringType , IntegerType , FloatType
from pyspark.sql import SparkSession
from pyspark.sql.functions import *


# CRIANDO SESSÃO DO SPARK 

spark = (SparkSession.builder
        .master("local(*)")
        .appName('pyspark-11')
        .getOrCreate()
        )

In [0]:
# CRIANDO DATAFRAME 

dados = (

    ['James','Vendas','NY',90000,34,10000],
    ['Michael','Vendas','NY',86000,56,20000],
    ['Robert','Vendas','CA',81000,30,23000],
    ['Maria','Financas','CA',90000,24,23000]
)


colunas = (StructType([
    StructField('Nome' , StringType(), True),
    StructField('Departamento' , StringType(), True),
    StructField('Estado' , StringType(), True),
    StructField('Salario' , IntegerType(), True),
    StructField('Idade' , IntegerType(), True),
    StructField('Bonus' , IntegerType(), True)
    
]))

## DATAFRAME FINAL 1

df1 = spark.createDataFrame(data = dados , schema = colunas)


# ============================== ++ ============================ ++ ==============================

# CRIANDO DATAFRAME 

dados1 = (

    ['James','Vendas','NY',90000,34,10000],
    ['Maria','Financas','CA',90000,24,23000],
    ['Jen','Financas','NY',79000,53,15000],
    ['Jeff','Marketing','CA',80000,25,18000],
    ['Kumar','Marketing','NY',91000,50,21000]
)


colunas1 = (StructType([
    StructField('Nome' , StringType(), True),
    StructField('Departamento' , StringType(), True),
    StructField('Estado' , StringType(), True),
    StructField('Salario' , IntegerType(), True),
    StructField('Idade' , IntegerType(), True),
    StructField('Bonus' , IntegerType(), True)
    
]))

## DATAFRAME FINAL 2

df2 = spark.createDataFrame(data = dados1 , schema = colunas1)

In [0]:
print('1 DATAFRAME')
df1.display()

1 DATAFRAME

Nome,Departamento,Estado,Salario,Idade,Bonus
James,Vendas,NY,90000,34,10000
Michael,Vendas,NY,86000,56,20000
Robert,Vendas,CA,81000,30,23000
Maria,Financas,CA,90000,24,23000

In [0]:
print('2 DATAFRAME')
df2.display()

2 DATAFRAME

Nome,Departamento,Estado,Salario,Idade,Bonus
James,Vendas,NY,90000,34,10000
Maria,Financas,CA,90000,24,23000
Jen,Financas,NY,79000,53,15000
Jeff,Marketing,CA,80000,25,18000
Kumar,Marketing,NY,91000,50,21000

In [0]:
print('União dos DOIS DATAFRAMES ')

uniao = df1.union(df2)

uniao.display()

União dos DOIS DATAFRAMES

Nome,Departamento,Estado,Salario,Idade,Bonus
James,Vendas,NY,90000,34,10000
Michael,Vendas,NY,86000,56,20000
Robert,Vendas,CA,81000,30,23000
Maria,Financas,CA,90000,24,23000
James,Vendas,NY,90000,34,10000
Maria,Financas,CA,90000,24,23000
Jen,Financas,NY,79000,53,15000
Jeff,Marketing,CA,80000,25,18000
Kumar,Marketing,NY,91000,50,21000

In [0]:
## 1) REMOVA OS VALORES (DUPLICADOS) SOBRE O DATAFRAME (UNIAO)

uniao.distinct().display()

Nome,Departamento,Estado,Salario,Idade,Bonus
James,Vendas,NY,90000,34,10000
Michael,Vendas,NY,86000,56,20000
Robert,Vendas,CA,81000,30,23000
Maria,Financas,CA,90000,24,23000
Jen,Financas,NY,79000,53,15000
Jeff,Marketing,CA,80000,25,18000
Kumar,Marketing,NY,91000,50,21000